#!/usr/bin/env bash

while getopts a:r: option
do
  case $option in
       a) 
          touch ~/Desktop/"${OPTARG} "`date +%Y-%m-%d`".md"
          ;;
       r)
          rm ~/Desktop/${OPTARG}.md
          ;;
       ?)
         echo "Usage: todo [-ar] [arg]"
         echo "-a add todo md file"
         echo "-r remove todo md file"
         exit
         ;;
   esac
done

# show the todo items
find ~/Desktop -name "*.md" | awk -F '/' '{print $NF}'
